// ===================== Chemistry 101: course content =====================
// Content is organised by AGE GROUP → TRACK → LESSON so that new age groups can be added later
// by pushing to AGE_GROUPS and adding COURSES[<id>]. Every text is {en, ro}.
const AGE_GROUPS = [ {id:'kids', name:L('Ages 8–18','Vârsta 8–18')} ];
let AGE = store.get('age', 'kids'); if(!AGE_GROUPS.some(a => a.id === AGE)) AGE = AGE_GROUPS[0].id;

// helpers: slide, term, question
const MI = key => MISSIONS.findIndex(m => m.key === key);

const COURSES = {};
COURSES.kids = [
 {id:'basics', name:L('Chemistry 101: the basics','Chimie 101: noțiunile de bază'), sub:L('Atoms, molecules and bonds','Atomi, molecule și legături'), lessons:[
  {id:'matter', title:L('What is everything made of?','Din ce e făcut totul?'),
   slides:[
    sl({type:'states'}, 'Everything around you is matter: your desk, the air, a glass of water and even you. Matter is anything that has mass and takes up space.', 'Tot ce te înconjoară este materie: banca ta, aerul, un pahar cu apă și chiar tu. Materia este orice are masă și ocupă loc.', 'Matter is everywhere', 'Materia e peste tot'),
    sl({type:'states'}, 'Matter is made of incredibly tiny particles that are always moving. In a solid they are packed tightly and only wiggle. In a liquid they slide past each other. In a gas they zoom around freely.', 'Materia este formată din particule incredibil de mici, care se mișcă mereu. Într-un solid sunt strânse și doar vibrează. Într-un lichid alunecă unele pe lângă altele. Într-un gaz zboară liber în toate direcțiile.', 'Solid, liquid, gas', 'Solid, lichid, gaz'),
    sl({type:'states', heat:1}, 'Heating gives particles more energy, so they move faster. That is why ice melts into water and water boils into steam. Cooling does the opposite.', 'Încălzirea le dă particulelor mai multă energie, așa că se mișcă mai repede. De aceea gheața se topește în apă, iar apa fierbe și devine abur. Răcirea face invers.', 'Heat makes particles move', 'Căldura pune particulele în mișcare'),
   ],
   terms:[tm('matter','materie','anything that has mass and takes up space','orice are masă și ocupă loc'), tm('particle','particulă','a tiny piece of matter, far too small to see','o bucățică de materie, mult prea mică pentru a fi văzută'), tm('states of matter','stări de agregare','solid, liquid and gas','solid, lichid și gaz')],
   quiz:[qz('In which state do particles move most freely?','În ce stare se mișcă particulele cel mai liber?', [['solid','solid'],['liquid','lichid'],['gas','gaz']], 2, 'Gas particles have the most energy and fly around freely.','Particulele de gaz au cea mai multă energie și zboară liber.'),
         qz('What happens to particles when you heat them?','Ce se întâmplă cu particulele când le încălzești?', [['They move faster','Se mișcă mai repede'],['They stop moving','Se opresc'],['They disappear','Dispar']], 0, 'More energy means faster particles. That is how solids melt and liquids boil.','Mai multă energie înseamnă particule mai rapide. Așa se topesc solidele și fierb lichidele.')],
   try:{tab:'lab', mission:'rule:evaporate:salt', label:L('Boil water away in the lab','Fierbe apa în laborator')}},

  {id:'atom', title:L('What is an atom?','Ce este un atom?'),
   slides:[
    sl({type:'atom', z:1, zoomIn:1}, 'Cut anything into smaller and smaller pieces and you finally reach atoms: the tiny building blocks of everything. One grain of sand contains more atoms than there are grains of sand on all the beaches on Earth!', 'Dacă tai orice în bucăți tot mai mici, ajungi în final la atomi: cărămizile minuscule din care e făcut totul. Un singur grăunte de nisip conține mai mulți atomi decât sunt grăunțe de nisip pe toate plajele Pământului!', 'The smallest building blocks', 'Cele mai mici cărămizi'),
    sl({type:'atom', z:6, labels:1}, 'In the centre of an atom is the nucleus. It holds protons, which have a positive charge (+), and neutrons, which have no charge. Tiny electrons, with a negative charge (−), whizz around the nucleus.', 'În centrul atomului se află nucleul. El conține protoni, care au sarcină pozitivă (+), și neutroni, care nu au sarcină. Electroni minusculi, cu sarcină negativă (−), zboară în jurul nucleului.', 'Protons, neutrons, electrons', 'Protoni, neutroni, electroni'),
    sl({type:'atom', z:8, empty:1}, 'An atom is mostly empty space! If the nucleus were a marble in the middle of a football stadium, the electrons would be buzzing around the very top seats.', 'Atomul este în mare parte spațiu gol! Dacă nucleul ar fi o bilă în mijlocul unui stadion de fotbal, electronii ar zumzăi pe lângă cele mai de sus locuri din tribună.', 'Mostly empty space', 'Mai ales spațiu gol'),
    sl({type:'atom', z:8, charge:1}, 'Atoms normally have the same number of protons and electrons. The plus and minus charges cancel out, so a normal atom has no overall charge.', 'Atomii au în mod normal tot atâția protoni câți electroni. Sarcinile plus și minus se anulează, așa că un atom obișnuit nu are sarcină totală.', 'Balanced charges', 'Sarcini echilibrate'),
   ],
   terms:[tm('atom','atom','the smallest piece of an element','cea mai mică bucată dintr-un element'), tm('nucleus','nucleu','the tiny, heavy centre of an atom','centrul minuscul și greu al atomului'), tm('proton','proton','a positive particle in the nucleus','o particulă pozitivă din nucleu'), tm('neutron','neutron','a particle with no charge in the nucleus','o particulă fără sarcină din nucleu'), tm('electron','electron','a tiny negative particle around the nucleus','o particulă minusculă, negativă, din jurul nucleului')],
   quiz:[qz('Which particle has a negative charge?','Ce particulă are sarcină negativă?', [['proton','protonul'],['neutron','neutronul'],['electron','electronul']], 2, 'Electrons are negative, protons are positive and neutrons are neutral.','Electronii sunt negativi, protonii pozitivi, iar neutronii neutri.'),
         qz('Where are protons and neutrons found?','Unde se află protonii și neutronii?', [['In the nucleus','În nucleu'],['Flying around outside','Zboară pe dinafară'],['Only in gases','Doar în gaze']], 0, 'Protons and neutrons are packed together in the nucleus.','Protonii și neutronii sunt strânși împreună în nucleu.')],
   try:{tab:'atoms', label:L('Build an atom yourself','Construiește singur un atom')}},

  {id:'elements', title:L('Elements and the periodic table','Elementele și tabelul periodic'),
   slides:[
    sl({type:'ptable', hl:'all'}, 'An element is a substance made of only one kind of atom. Gold is only gold atoms and oxygen is only oxygen atoms. Scientists know 118 elements.', 'Un element este o substanță formată dintr-un singur fel de atom. Aurul este doar atomi de aur, iar oxigenul doar atomi de oxigen. Oamenii de știință cunosc 118 elemente.', 'One kind of atom', 'Un singur fel de atom'),
    sl({type:'compare', els:[1,6,8]}, 'What makes elements different? The number of protons! Every atom with 1 proton is hydrogen, every atom with 6 is carbon, and every atom with 8 is oxygen. This number is called the atomic number.', 'Ce face elementele diferite? Numărul de protoni! Orice atom cu 1 proton este hidrogen, orice atom cu 6 este carbon, iar orice atom cu 8 este oxigen. Acest număr se numește număr atomic.', 'Counting protons', 'Numărăm protonii'),
    sl({type:'ptable', hl:'order'}, 'Each element has a short symbol: H for hydrogen, O for oxygen, Na for sodium (from its Latin name, natrium). The periodic table lists all the elements in order of their atomic number.', 'Fiecare element are un simbol scurt: H pentru hidrogen, O pentru oxigen, Na pentru sodiu (din numele latin, natrium). Tabelul periodic așază toate elementele în ordinea numărului atomic.', 'Symbols and order', 'Simboluri și ordine'),
    sl({type:'ptable', hl:'groups'}, 'Elements in the same column, called a group, behave in similar ways. The first column holds very reactive metals. The last column holds the calm noble gases, which hardly react at all.', 'Elementele din aceeași coloană, numită grupă, se comportă asemănător. Prima coloană conține metale foarte reactive. Ultima coloană conține gazele nobile, liniștite, care aproape nu reacționează.', 'Families of elements', 'Familii de elemente'),
   ],
   terms:[tm('element','element','a substance made of one kind of atom','o substanță formată dintr-un singur fel de atom'), tm('atomic number','număr atomic','the number of protons in an atom','numărul de protoni dintr-un atom'), tm('symbol','simbol','a one- or two-letter name, like H or Na','un nume din una sau două litere, ca H sau Na'), tm('group','grupă','a column of the periodic table','o coloană a tabelului periodic')],
   quiz:[qz('What decides which element an atom is?','Ce decide ce element este un atom?', [['Its number of protons','Numărul de protoni'],['Its colour','Culoarea'],['Its size','Mărimea']], 0, 'The atomic number, the number of protons, is the element’s identity card.','Numărul atomic, adică numărul de protoni, este buletinul elementului.'),
         qz('What is the symbol of sodium?','Care este simbolul sodiului?', [['So','So'],['Na','Na'],['S','S']], 1, 'Na comes from the Latin name natrium. S is sulfur.','Na vine din numele latin natrium. S este sulful.')],
   try:{tab:'atoms', label:L('Explore the first 20 elements','Explorează primele 20 de elemente')}},

  {id:'molecules', title:L('What is a molecule?','Ce este o moleculă?'),
   slides:[
    sl({type:'molecules', list:['H2','O2','N2']}, 'When atoms join together, they make a molecule. Two oxygen atoms joined together make an oxygen molecule, O₂, the oxygen you breathe.', 'Când atomii se unesc, formează o moleculă. Doi atomi de oxigen uniți formează o moleculă de oxigen, O₂, oxigenul pe care îl respiri.', 'Atoms holding hands', 'Atomi care se țin de mână'),
    sl({type:'molecules', list:['H2O','CO2','CH4']}, 'When atoms of different elements join, they make a compound. Water, H₂O, is two hydrogen atoms joined to one oxygen atom. The small numbers tell you how many atoms of each kind there are.', 'Când se unesc atomi ai unor elemente diferite, formează un compus. Apa, H₂O, înseamnă doi atomi de hidrogen uniți cu un atom de oxigen. Cifrele mici îți spun câți atomi din fiecare fel există.', 'Compounds and formulas', 'Compuși și formule'),
    sl({type:'elemcomp'}, 'A compound can be totally different from its elements. Hydrogen is a gas that burns and oxygen helps things burn, yet together they make water, which puts fires out!', 'Un compus poate fi complet diferit de elementele lui. Hidrogenul este un gaz care arde, iar oxigenul ajută arderea, totuși împreună formează apa, care stinge focul!', 'Element, compound, mixture', 'Element, compus, amestec'),
   ],
   terms:[tm('molecule','moleculă','two or more atoms joined together','doi sau mai mulți atomi uniți'), tm('compound','compus','a substance made of different elements joined together','o substanță formată din elemente diferite unite'), tm('chemical formula','formulă chimică','letters and numbers showing the atoms in a substance, like H₂O','litere și cifre care arată atomii dintr-o substanță, ca H₂O')],
   quiz:[qz('How many atoms are in one H₂O molecule?','Câți atomi are o moleculă de H₂O?', [['2','2'],['3','3'],['4','4']], 1, 'Two hydrogen atoms plus one oxygen atom make three.','Doi atomi de hidrogen plus un atom de oxigen fac trei.'),
         qz('Which one is a compound?','Care dintre ele este un compus?', [['O₂','O₂'],['H₂','H₂'],['CO₂','CO₂']], 2, 'CO₂ is made of two different elements, carbon and oxygen.','CO₂ este format din două elemente diferite, carbon și oxigen.')],
   try:{tab:'molecules', label:L('Build molecules','Construiește molecule')}},

  {id:'bond', title:L('What is a chemical bond?','Ce este o legătură chimică?'),
   slides:[
    sl({type:'bondshare'}, 'A chemical bond is what holds atoms together. Bonds are made by electrons, the tiny particles on the outside of atoms.', 'Legătura chimică este ceea ce ține atomii împreună. Legăturile sunt făcute de electroni, particulele minuscule de pe exteriorul atomilor.', 'The glue between atoms', 'Lipiciul dintre atomi'),
    sl({type:'shells', els:[1,6,8,10]}, 'Electrons live in layers called shells. Atoms are most stable, or “happy”, when their outer shell is full: 2 electrons in the first shell and 8 in the next ones.', 'Electronii stau pe niveluri numite straturi. Atomii sunt cei mai stabili, adică „fericiți”, când stratul exterior e complet: 2 electroni pe primul strat și 8 pe următoarele.', 'Electron shells', 'Straturi de electroni'),
    sl({type:'bondshare'}, 'To fill their outer shells, atoms can share electrons or give and take them. Either way they end up stuck together, and that connection is a bond.', 'Ca să-și completeze stratul exterior, atomii pot împărți electroni sau îi pot da și primi. Oricum ar fi, ajung lipiți unul de altul, iar această legătură se numește legătură chimică.', 'Sharing or swapping', 'Împărțire sau schimb'),
    sl({type:'shells', els:[2,10,18]}, 'Noble gases like helium and neon already have full shells, so they don’t need to bond. That is why they almost never react.', 'Gazele nobile, ca heliul și neonul, au deja straturile complete, așa că nu au nevoie de legături. De aceea aproape niciodată nu reacționează.', 'The happy noble gases', 'Gazele nobile, mereu mulțumite'),
   ],
   terms:[tm('chemical bond','legătură chimică','a force that holds atoms together','o forță care ține atomii împreună'), tm('electron shell','strat de electroni','a layer where electrons live around the nucleus','un nivel pe care stau electronii în jurul nucleului'), tm('outer electrons','electroni exteriori','the electrons in the outer shell, which make bonds','electronii de pe stratul exterior, care fac legăturile')],
   quiz:[qz('Which particles make chemical bonds?','Ce particule fac legăturile chimice?', [['protons','protonii'],['electrons','electronii'],['neutrons','neutronii']], 1, 'Bonds are all about the outer electrons.','Legăturile țin de electronii exteriori.'),
         qz('Why does neon hardly react?','De ce neonul aproape nu reacționează?', [['Its outer shell is already full','Are stratul exterior deja complet'],['It is too heavy','Este prea greu'],['It has no electrons','Nu are electroni']], 0, 'A full outer shell means no need to share or swap electrons.','Un strat exterior complet înseamnă că nu trebuie să împartă sau să schimbe electroni.')],
   try:{tab:'molecules', label:L('Watch atoms bond','Privește atomii legându-se')}},

  {id:'bondtypes', title:L('Types of bonds','Tipuri de legături'),
   slides:[
    sl({type:'bondshare', label:'covalent'}, 'Covalent bond: atoms share pairs of electrons. This usually happens between non-metals, like in water, oxygen and sugar. Two shared pairs make a double bond, and three make a triple bond.', 'Legătura covalentă: atomii împart perechi de electroni. Se întâmplă de obicei între nemetale, ca în apă, oxigen și zahăr. Două perechi comune fac o legătură dublă, iar trei o legătură triplă.', '1. Covalent: sharing', '1. Covalentă: împărțire'),
    sl({type:'bondionic'}, 'Ionic bond: a metal atom gives electrons to a non-metal atom. They become ions with opposite charges, which attract each other like magnets. Table salt, NaCl, is held together this way.', 'Legătura ionică: un atom de metal dă electroni unui atom de nemetal. Devin ioni cu sarcini opuse, care se atrag ca niște magneți. Sarea de bucătărie, NaCl, este ținută astfel.', '2. Ionic: giving and taking', '2. Ionică: dăruire și primire'),
    sl({type:'bondmetal'}, 'Metallic bond: in metals, the outer electrons leave their atoms and flow around freely, like a sea of electrons around positive ions. That is why metals conduct electricity and can be bent without breaking.', 'Legătura metalică: în metale, electronii exteriori își părăsesc atomii și circulă liber, ca o mare de electroni în jurul ionilor pozitivi. De aceea metalele conduc curentul electric și pot fi îndoite fără să se rupă.', '3. Metallic: a sea of electrons', '3. Metalică: o mare de electroni'),
    sl({type:'hbond'}, 'Between molecules there are weaker pulls too, such as hydrogen bonds between water molecules. They are why water sticks together in drops.', 'Între molecule există și atracții mai slabe, cum sunt legăturile de hidrogen dintre moleculele de apă. Datorită lor apa se adună în picături.', 'Bonus: pulls between molecules', 'Bonus: atracții între molecule'),
   ],
   terms:[tm('covalent bond','legătură covalentă','atoms share electrons','atomii împart electroni'), tm('ionic bond','legătură ionică','one atom gives electrons to another; opposite ions attract','un atom dă electroni altuia; ionii opuși se atrag'), tm('metallic bond','legătură metalică','metal ions in a sea of free electrons','ioni metalici într-o mare de electroni liberi'), tm('ion','ion','an atom with a charge','un atom cu sarcină electrică')],
   quiz:[qz('In table salt, the bond is…','În sarea de bucătărie, legătura este…', [['covalent','covalentă'],['ionic','ionică'],['metallic','metalică']], 1, 'Sodium gives an electron to chlorine: Na⁺ and Cl⁻ attract.','Sodiul dă un electron clorului: Na⁺ și Cl⁻ se atrag.'),
         qz('Why do metals conduct electricity?','De ce conduc metalele curentul electric?', [['Their electrons can move freely','Electronii lor se pot mișca liber'],['They are cold','Sunt reci'],['They are shiny','Sunt lucioase']], 0, 'Electric current is moving electrons, and metals have a sea of free ones.','Curentul electric înseamnă electroni în mișcare, iar metalele au o mare de electroni liberi.'),
         qz('How many electron pairs are shared in a double bond?','Câte perechi de electroni se împart într-o legătură dublă?', [['1','1'],['2','2'],['3','3']], 1, 'Double bond, two shared pairs, as in O₂ and CO₂.','Legătură dublă, două perechi comune, ca în O₂ și CO₂.')],
   try:{tab:'molecules', label:L('Build covalent and ionic molecules','Construiește molecule covalente și ionice')}},

  {id:'mixtures', title:L('Mixtures and solutions','Amestecuri și soluții'),
   slides:[
    sl({type:'elemcomp', focus:2}, 'A mixture is two or more substances mixed together but not chemically joined. Each one keeps its own properties, like sand mixed with iron filings, or a salad.', 'Un amestec înseamnă două sau mai multe substanțe amestecate, dar nelegate chimic. Fiecare își păstrează proprietățile, ca nisipul amestecat cu pilitură de fier sau o salată.', 'Mixed, not joined', 'Amestecate, nu legate'),
    sl({type:'dissolve'}, 'When salt or sugar dissolves in water, it breaks into particles too small to see and spreads out evenly. This special mixture is called a solution. The salt is the solute and the water is the solvent.', 'Când sarea sau zahărul se dizolvă în apă, se desfac în particule prea mici ca să fie văzute și se împrăștie uniform. Acest amestec special se numește soluție. Sarea este solutul, iar apa este solventul.', 'Dissolving', 'Dizolvarea'),
    sl({type:'evap'}, 'Mixtures can be separated by physical methods: a filter catches sand, a magnet pulls out iron, and boiling the water away leaves the salt behind.', 'Amestecurile pot fi separate prin metode fizice: filtrul oprește nisipul, magnetul scoate fierul, iar dacă fierbi apa până se evaporă, sarea rămâne în urmă.', 'Separating mixtures', 'Separarea amestecurilor'),
   ],
   terms:[tm('mixture','amestec','substances mixed but not chemically joined','substanțe amestecate, dar nelegate chimic'), tm('solution','soluție','a mixture where one substance is dissolved evenly in another','un amestec în care o substanță este dizolvată uniform în alta'), tm('solute / solvent','solut / solvent','what dissolves / what it dissolves in','ce se dizolvă / în ce se dizolvă')],
   quiz:[qz('In salt water, what is the solvent?','În apa sărată, care este solventul?', [['salt','sarea'],['water','apa'],['air','aerul']], 1, 'The solvent is the liquid that does the dissolving: water.','Solventul este lichidul care dizolvă: apa.'),
         qz('How can you get salt back from salt water?','Cum poți recupera sarea din apa sărată?', [['Boil the water away','Fierbi apa până se evaporă'],['Use a magnet','Folosești un magnet'],['Add sand','Adaugi nisip']], 0, 'Water evaporates, but salt cannot, so it stays behind.','Apa se evaporă, dar sarea nu poate, așa că rămâne.')],
   try:{tab:'lab', mission:'rule:salt_dissolve', label:L('Dissolve salt in the lab','Dizolvă sare în laborator')}},

  {id:'changes', title:L('Physical and chemical changes','Transformări fizice și chimice'),
   slides:[
    sl({type:'change', side:0}, 'In a physical change, a substance changes its shape or state but stays the same substance. Melted ice is still water. Torn paper is still paper.', 'Într-o transformare fizică, o substanță își schimbă forma sau starea, dar rămâne aceeași substanță. Gheața topită este tot apă. Hârtia ruptă este tot hârtie.', 'Physical change', 'Transformare fizică'),
    sl({type:'change', side:1}, 'In a chemical change, also called a chemical reaction, new substances are made. Burning wood makes ash, smoke and gases. Baking a cake, rusting and digesting food are chemical changes too.', 'Într-o transformare chimică, numită și reacție chimică, se formează substanțe noi. Lemnul care arde face cenușă, fum și gaze. Coacerea unei prăjituri, ruginirea și digestia sunt tot transformări chimice.', 'Chemical change', 'Transformare chimică'),
    sl({type:'signs'}, 'How can you spot a reaction? Look for the signs: bubbles of gas, a colour change, a new solid appearing, heat or cold, light, or a new smell.', 'Cum recunoști o reacție? Caută semnele: bule de gaz, schimbare de culoare, un solid nou, căldură sau răcire, lumină ori un miros nou.', 'Signs of a reaction', 'Semnele unei reacții'),
   ],
   terms:[tm('physical change','transformare fizică','same substance, new shape or state','aceeași substanță, altă formă sau stare'), tm('chemical change','transformare chimică','new substances are made','se formează substanțe noi'), tm('chemical reaction','reacție chimică','another name for a chemical change','alt nume pentru transformarea chimică')],
   quiz:[qz('Which one is a chemical change?','Care este o transformare chimică?', [['Ice melting','Gheața care se topește'],['A candle burning','O lumânare care arde'],['Sugar dissolving','Zahărul care se dizolvă']], 1, 'Burning makes new substances: carbon dioxide and water vapour.','Arderea face substanțe noi: dioxid de carbon și vapori de apă.'),
         qz('Which is NOT a sign of a reaction?','Care NU este un semn de reacție?', [['A new colour','O culoare nouă'],['Bubbles of gas','Bule de gaz'],['Pouring water into another glass','Turnarea apei în alt pahar']], 2, 'Pouring only moves the water; nothing new is made.','Turnarea doar mută apa; nu se formează nimic nou.')],
   try:{tab:'lab', mission:'rule:acid_carb:vinegar:soda', label:L('Make a kitchen volcano','Fă un vulcan din bucătărie')}},
 ]},

 {id:'next', name:L('Next steps','Pasul următor'), sub:L('Reactions, acids, ions and energy','Reacții, acizi, ioni și energie'), lessons:[
  {id:'reactions', title:L('Reactions and equations','Reacții și ecuații'),
   slides:[
    sl({type:'reaction', spec:{from:['H2','H2','O2'], to:['H2O','H2O']}}, 'In a reaction, the starting substances are called reactants and the new ones are products. We write: reactants → products. The arrow means “turn into”.', 'Într-o reacție, substanțele de la început se numesc reactanți, iar cele noi produși. Scriem: reactanți → produși. Săgeata înseamnă „se transformă în”.', 'Reactants and products', 'Reactanți și produși'),
    sl({type:'reaction', spec:{from:['H2','H2','O2'], to:['H2O','H2O']}}, 'Atoms are never created or destroyed in a reaction. They only swap partners. So the total mass at the start equals the total mass at the end. This is the law of conservation of mass.', 'Într-o reacție atomii nu se creează și nu se distrug. Doar își schimbă partenerii. Deci masa totală de la început este egală cu masa totală de la sfârșit. Aceasta este legea conservării masei.', 'Nothing is lost', 'Nimic nu se pierde'),
    sl({type:'reaction', spec:{from:['CH4','O2','O2'], to:['CO2','H2O','H2O']}}, 'That is why equations must be balanced, with the same number of each atom on both sides. When methane burns: CH₄ + 2O₂ → CO₂ + 2H₂O. Count them: 1 carbon, 4 hydrogens and 4 oxygens on each side.', 'De aceea ecuațiile trebuie egalate, cu același număr din fiecare atom de ambele părți. Când arde metanul: CH₄ + 2O₂ → CO₂ + 2H₂O. Numără: 1 carbon, 4 hidrogeni și 4 oxigeni de fiecare parte.', 'Balancing equations', 'Egalarea ecuațiilor'),
   ],
   terms:[tm('reactant','reactant','a substance you start with','o substanță cu care începi'), tm('product','produs','a new substance made in a reaction','o substanță nouă formată în reacție'), tm('conservation of mass','conservarea masei','atoms are not created or destroyed','atomii nu se creează și nu se distrug'), tm('balanced equation','ecuație egalată','same number of each atom on both sides','același număr din fiecare atom de ambele părți')],
   quiz:[qz('In 2H₂ + O₂ → 2H₂O, what is the product?','În 2H₂ + O₂ → 2H₂O, care este produsul?', [['H₂ and O₂','H₂ și O₂'],['H₂O','H₂O'],['Nothing','Nimic']], 1, 'Products come after the arrow: water.','Produșii sunt după săgeată: apa.'),
         qz('During a reaction, atoms…','În timpul unei reacții, atomii…', [['disappear','dispar'],['rearrange','se rearanjează'],['turn into other elements','devin alte elemente']], 1, 'Atoms swap partners, but each atom stays the same element.','Atomii își schimbă partenerii, dar fiecare rămâne același element.')],
   try:{tab:'lab', mission:'rule:acid_carb:vinegar:soda', label:L('Watch atoms swap partners in the lab','Privește atomii schimbându-și partenerii în laborator')}},

  {id:'acids', title:L('Acids, bases and pH','Acizi, baze și pH'),
   slides:[
    sl({type:'phscale'}, 'Acids taste sour, like lemon juice and vinegar. Bases feel slippery and taste bitter, like soap and baking soda. (Never taste anything in a real lab!)', 'Acizii au gust acru, ca sucul de lămâie și oțetul. Bazele sunt alunecoase și au gust amar, ca săpunul și bicarbonatul. (Într-un laborator adevărat nu gusta niciodată nimic!)', 'Sour and slippery', 'Acru și alunecos'),
    sl({type:'phscale', marks:1}, 'The pH scale measures how acidic or basic something is, from 0 to 14. Below 7 is acidic, 7 is neutral like pure water, and above 7 is basic, also called alkaline.', 'Scara pH măsoară cât de acid sau bazic este ceva, de la 0 la 14. Sub 7 este acid, 7 este neutru, ca apa pură, iar peste 7 este bazic, numit și alcalin.', 'The pH scale', 'Scara pH'),
    sl({type:'phscale', cabbage:1}, 'In water, acids release H⁺ ions and bases release OH⁻ ions. Indicators such as red cabbage juice change colour to show the pH.', 'În apă, acizii eliberează ioni H⁺, iar bazele ioni OH⁻. Indicatorii, cum ar fi sucul de varză roșie, își schimbă culoarea ca să arate pH-ul.', 'Colour detectives', 'Detectivii culorilor'),
    sl({type:'reaction', spec:{from:['H+','OH-'], to:['H2O']}}, 'When an acid and a base meet, H⁺ and OH⁻ join to make water. This is called neutralisation, and it also makes a salt.', 'Când un acid întâlnește o bază, H⁺ și OH⁻ se unesc și formează apă. Aceasta se numește neutralizare și formează totodată o sare.', 'Neutralisation', 'Neutralizarea'),
   ],
   terms:[tm('acid','acid','a substance with pH below 7 that releases H⁺','o substanță cu pH sub 7 care eliberează H⁺'), tm('base (alkali)','bază','a substance with pH above 7 that releases OH⁻','o substanță cu pH peste 7 care eliberează OH⁻'), tm('pH','pH','a 0–14 scale of how acidic or basic something is','o scară de la 0 la 14 a acidității'), tm('indicator','indicator','a substance that changes colour with pH','o substanță care își schimbă culoarea după pH')],
   quiz:[qz('pH 7 is…','pH 7 înseamnă…', [['acidic','acid'],['neutral','neutru'],['basic','bazic']], 1, 'Seven is right in the middle: neutral, like pure water.','Șapte este exact la mijloc: neutru, ca apa pură.'),
         qz('Which of these is a base?','Care dintre acestea este o bază?', [['Lemon juice','Sucul de lămâie'],['Vinegar','Oțetul'],['Soap','Săpunul']], 2, 'Soap is slippery and has a pH around 9–10.','Săpunul este alunecos și are pH în jur de 9–10.'),
         qz('An acid plus a base makes…','Un acid plus o bază formează…', [['a salt and water','o sare și apă'],['gold','aur'],['only gas','doar gaz']], 0, 'That is neutralisation: H⁺ + OH⁻ → H₂O, plus a salt.','Aceasta este neutralizarea: H⁺ + OH⁻ → H₂O, plus o sare.')],
   try:{tab:'lab', mission:'indicator:acid', label:L('Play colour detective in the lab','Joacă-te de-a detectivul culorilor în laborator')}},

  {id:'ions', title:L('Ions and salts','Ioni și săruri'),
   slides:[
    sl({type:'bondionic'}, 'An ion is an atom that has lost or gained electrons, so it has a charge. Losing electrons makes a positive ion. Gaining electrons makes a negative ion.', 'Un ion este un atom care a pierdut sau a câștigat electroni, așa că are sarcină. Pierderea de electroni face un ion pozitiv. Câștigarea de electroni face un ion negativ.', 'Charged atoms', 'Atomi încărcați'),
    sl({type:'shells', els:[11,17]}, 'Metals like sodium have few outer electrons and lose them easily: Na becomes Na⁺. Non-metals like chlorine need just one more, and gain it: Cl becomes Cl⁻.', 'Metalele, ca sodiul, au puțini electroni exteriori și îi pierd ușor: Na devine Na⁺. Nemetalele, ca clorul, mai au nevoie de unul singur și îl câștigă: Cl devine Cl⁻.', 'Who loses, who gains', 'Cine pierde, cine câștigă'),
    sl({type:'lattice'}, 'Positive and negative ions attract each other and stack into a regular pattern called a crystal lattice. That is why grains of salt are tiny cubes.', 'Ionii pozitivi și negativi se atrag și se așază într-un model regulat, numit rețea cristalină. De aceea grăunțele de sare sunt niște cubulețe.', 'Crystal patterns', 'Modele de cristale'),
   ],
   terms:[tm('ion','ion','an atom with a charge','un atom cu sarcină'), tm('cation','cation','a positive ion, like Na⁺','un ion pozitiv, ca Na⁺'), tm('anion','anion','a negative ion, like Cl⁻','un ion negativ, ca Cl⁻'), tm('crystal lattice','rețea cristalină','a regular 3D pattern of particles','un model 3D regulat de particule')],
   quiz:[qz('An atom that gains an electron becomes…','Un atom care câștigă un electron devine…', [['a positive ion','un ion pozitiv'],['a negative ion','un ion negativ'],['a neutron','un neutron']], 1, 'Electrons are negative, so one extra makes the atom negative.','Electronii sunt negativi, deci unul în plus face atomul negativ.'),
         qz('Why are salt grains cube-shaped?','De ce grăunțele de sare au formă de cub?', [['The ions stack in a regular pattern','Ionii se așază într-un model regulat'],['They are cut in factories','Sunt tăiate în fabrici'],['Water shapes them','Apa le modelează']], 0, 'Na⁺ and Cl⁻ stack in a cube-shaped lattice.','Na⁺ și Cl⁻ se așază într-o rețea în formă de cub.')],
   try:{tab:'lab', mission:'rule:agno3_cl', label:L('Make a cloud of solid ions','Fă un nor de ioni solizi')}},

  {id:'energy', title:L('Energy in reactions','Energia în reacții'),
   slides:[
    sl({type:'energy', mode:'exo'}, 'Breaking bonds needs energy and making bonds releases energy. If more energy is released than used, the reaction gives off heat. It is exothermic, like burning or a hand warmer.', 'Ruperea legăturilor cere energie, iar formarea lor eliberează energie. Dacă se eliberează mai multă energie decât se consumă, reacția degajă căldură. Este exotermă, ca arderea sau un încălzitor de mâini.', 'Exothermic: gets hot', 'Exotermă: se încălzește'),
    sl({type:'energy', mode:'endo'}, 'If more energy is used than released, the reaction takes in heat and feels cold. It is endothermic, like an instant cold pack.', 'Dacă se consumă mai multă energie decât se eliberează, reacția absoarbe căldură și pare rece. Este endotermă, ca o pungă rece instant.', 'Endothermic: gets cold', 'Endotermă: se răcește'),
    sl({type:'energy', mode:'exo', act:1}, 'Most reactions need a push to get started, like a ball that must be rolled over a hill. This starting energy is called the activation energy. A match gives it to a candle.', 'Majoritatea reacțiilor au nevoie de un impuls ca să pornească, ca o minge care trebuie împinsă peste un deal. Această energie de pornire se numește energie de activare. Chibritul i-o dă lumânării.', 'Activation energy', 'Energia de activare'),
   ],
   terms:[tm('exothermic','exotermă','gives off heat','degajă căldură'), tm('endothermic','endotermă','takes in heat','absoarbe căldură'), tm('activation energy','energie de activare','the energy needed to start a reaction','energia necesară pentru a porni o reacție')],
   quiz:[qz('A reaction that gets hot is…','O reacție care se încălzește este…', [['endothermic','endotermă'],['exothermic','exotermă'],['neutral','neutră']], 1, 'Exo means “out”: heat goes out.','Exo înseamnă „în afară”: căldura iese.'),
         qz('Why does a candle need a match?','De ce lumânarea are nevoie de un chibrit?', [['To give it activation energy','Ca să primească energie de activare'],['To add more wax','Ca să aibă mai multă ceară'],['To make it cold','Ca s-o răcească']], 0, 'The match pushes the reaction over the energy hill; then it keeps itself going.','Chibritul împinge reacția peste dealul energetic; apoi ea continuă singură.')],
   try:{tab:'lab', mission:'rule:mg_burn', label:L('Try the magnesium flash','Încearcă blitul de magneziu')}},

  {id:'rates', title:L('Reaction speed and catalysts','Viteza reacțiilor și catalizatorii'),
   slides:[
    sl({type:'collisions'}, 'To react, particles must bump into each other hard enough. More bumps mean a faster reaction.', 'Ca să reacționeze, particulele trebuie să se ciocnească suficient de puternic. Mai multe ciocniri înseamnă o reacție mai rapidă.', 'Collisions', 'Ciocniri'),
    sl({type:'collisions', two:1}, 'You can speed up a reaction by heating it (faster particles), making it more concentrated (more particles), or breaking solids into small pieces (more surface to hit).', 'Poți grăbi o reacție încălzind-o (particule mai rapide), făcând-o mai concentrată (mai multe particule) sau sfărâmând solidele în bucăți mici (mai multă suprafață de lovit).', 'Speeding things up', 'Cum grăbim reacțiile'),
    sl({type:'energy', mode:'exo', cat:1}, 'A catalyst speeds up a reaction without being used up. It gives the reaction an easier path with a lower hill. The yeast in elephant toothpaste is a catalyst, and the enzymes in your body are too.', 'Un catalizator grăbește o reacție fără să se consume. Îi oferă reacției o cale mai ușoară, cu un deal mai mic. Drojdia din pasta de dinți pentru elefanți este un catalizator, la fel și enzimele din corpul tău.', 'Catalysts', 'Catalizatorii'),
   ],
   terms:[tm('reaction rate','viteză de reacție','how fast a reaction happens','cât de repede are loc o reacție'), tm('collision','ciocnire','particles bumping into each other','particule care se lovesc'), tm('catalyst','catalizator','speeds up a reaction and is not used up','grăbește o reacție și nu se consumă'), tm('enzyme','enzimă','a catalyst made by living things','un catalizator produs de ființele vii')],
   quiz:[qz('What does a catalyst do?','Ce face un catalizator?', [['Speeds up a reaction and is not used up','Grăbește reacția și nu se consumă'],['Slows a reaction down','Încetinește reacția'],['Becomes a product','Devine produs']], 0, 'A catalyst lowers the energy hill and comes out unchanged.','Catalizatorul coboară dealul energetic și iese neschimbat.'),
         qz('Why does powder react faster than a lump?','De ce pulberea reacționează mai repede decât o bucată?', [['More surface area','Are mai multă suprafață'],['It is heavier','Este mai grea'],['It is colder','Este mai rece']], 0, 'More surface means more places for particles to collide.','Mai multă suprafață înseamnă mai multe locuri pentru ciocniri.')],
   try:{tab:'lab', mission:'rule:h2o2_yeast:soap', label:L('Make elephant toothpaste','Fă pastă de dinți pentru elefanți')}},
 ]},

 {id:'advanced', name:L('Advanced','Avansat'), sub:L('Trends, moles, redox and carbon','Reguli, moli, redox și carbon'), lessons:[
  {id:'periodic', title:L('Shells and periodic patterns','Straturi și regulile tabelului periodic'),
   slides:[
    sl({type:'shells', els:[3,11,19]}, 'The row, or period, of an element tells you how many electron shells it has. The column, or group, tells you how many outer electrons it has.', 'Rândul, adică perioada, unui element îți spune câte straturi de electroni are. Coloana, adică grupa, îți spune câți electroni exteriori are.', 'Periods and groups', 'Perioade și grupe'),
    sl({type:'shells', els:[3,11,19], glow:1}, 'Group 1 metals all have 1 outer electron. Going down the group, atoms get bigger and the outer electron is further from the nucleus, so it is easier to lose. Reactivity increases: lithium fizzes, sodium zooms, potassium burns and caesium explodes.', 'Toate metalele din grupa 1 au 1 electron exterior. Coborând în grupă, atomii devin mai mari, iar electronul exterior e mai departe de nucleu, deci se pierde mai ușor. Reactivitatea crește: litiul sfârâie, sodiul aleargă, potasiul arde, iar cesiul explodează.', 'Down group 1', 'În jos în grupa 1'),
    sl({type:'shells', els:[9,17]}, 'Group 17, the halogens, need one more electron. Here it is the opposite: the smaller atoms at the top grab electrons best, so fluorine is the most reactive of all.', 'Grupa 17, halogenii, mai au nevoie de un electron. Aici e invers: atomii mai mici de sus atrag cel mai bine electroni, așa că fluorul este cel mai reactiv dintre toți.', 'The halogens', 'Halogenii'),
   ],
   terms:[tm('period','perioadă','a row of the periodic table = number of shells','un rând al tabelului periodic = numărul de straturi'), tm('group','grupă','a column = number of outer electrons (for main groups)','o coloană = numărul de electroni exteriori (la grupele principale)'), tm('reactivity','reactivitate','how easily a substance reacts','cât de ușor reacționează o substanță'), tm('halogens','halogeni','group 17: F, Cl, Br, I','grupa 17: F, Cl, Br, I')],
   quiz:[qz('Why is potassium more reactive than sodium?','De ce potasiul este mai reactiv decât sodiul?', [['Its outer electron is further from the nucleus','Electronul exterior este mai departe de nucleu'],['It is lighter','Este mai ușor'],['It has more neutrons','Are mai mulți neutroni']], 0, 'A distant electron is held weakly, so it is lost easily.','Un electron îndepărtat este ținut slab, deci se pierde ușor.'),
         qz('How many outer electrons do group 1 atoms have?','Câți electroni exteriori au atomii din grupa 1?', [['1','1'],['2','2'],['8','8']], 0, 'One lonely outer electron, which they are keen to lose.','Un singur electron exterior, pe care vor să-l piardă.')],
   try:{tab:'lab', mission:'rule:cs_water', label:L('Compare Li, Na, K and Cs in water','Compară Li, Na, K și Cs în apă')}},

  {id:'mole', title:L('Counting atoms: the mole','Numărarea atomilor: molul'),
   slides:[
    sl({type:'mole', stage:0}, 'Atoms are far too small to count one by one, so chemists count them in huge packs called moles, just as we count eggs in dozens.', 'Atomii sunt mult prea mici ca să fie numărați unul câte unul, așa că chimiștii îi numără în pachete uriașe numite moli, la fel cum numărăm ouăle în duzini.', 'A chemist’s dozen', 'Duzina chimistului'),
    sl({type:'mole', stage:1}, 'One mole is 602,214,076,000,000,000,000,000 particles: 6.022 × 10²³. This is called Avogadro’s number.', 'Un mol înseamnă 602.214.076.000.000.000.000.000 de particule: 6,022 × 10²³. Acesta se numește numărul lui Avogadro.', 'Avogadro’s number', 'Numărul lui Avogadro'),
    sl({type:'mole', stage:2}, 'One mole of a substance weighs its formula mass in grams. A mole of carbon is 12 g and a mole of water is 18 g: about one big spoonful, yet it holds 6 × 10²³ molecules!', 'Un mol dintr-o substanță cântărește cât masa ei moleculară, în grame. Un mol de carbon are 12 g, iar un mol de apă 18 g: cam o lingură mare, dar conține 6 × 10²³ molecule!', 'Molar mass', 'Masa molară'),
   ],
   terms:[tm('mole','mol','6.022 × 10²³ particles','6,022 × 10²³ particule'), tm('Avogadro’s number','numărul lui Avogadro','6.022 × 10²³','6,022 × 10²³'), tm('molar mass','masă molară','the mass of one mole, in g/mol','masa unui mol, în g/mol')],
   quiz:[qz('About how much does one mole of water weigh?','Cât cântărește aproximativ un mol de apă?', [['18 g','18 g'],['1 kg','1 kg'],['1 g','1 g']], 0, 'H₂O: 2 × 1 + 16 = 18, so 18 g.','H₂O: 2 × 1 + 16 = 18, deci 18 g.'),
         qz('A mole is a way to…','Molul este un mod de a…', [['count particles','număra particule'],['measure temperature','măsura temperatura'],['measure pH','măsura pH-ul']], 0, 'It is the chemist’s counting unit.','Este unitatea de numărare a chimistului.')],
   try:{tab:'molecules', label:L('Build H₂O and count its atoms','Construiește H₂O și numără-i atomii')}},

  {id:'redox', title:L('Oxidation and reduction','Oxidare și reducere'),
   slides:[
    sl({type:'redox'}, 'Many reactions are about electrons moving from one substance to another. Losing electrons is called oxidation. Gaining electrons is called reduction. Remember OIL RIG: Oxidation Is Loss, Reduction Is Gain.', 'Multe reacții înseamnă electroni care trec de la o substanță la alta. Pierderea de electroni se numește oxidare. Câștigarea de electroni se numește reducere. Ține minte: oxidarea pierde, reducerea primește.', 'Losing and gaining electrons', 'Pierdere și câștig de electroni'),
    sl({type:'redox'}, 'In the iron nail experiment, iron atoms lose 2 electrons (oxidation) and copper ions gain them (reduction). One can’t happen without the other, which is why we call it a redox reaction.', 'În experimentul cu cuiul de fier, atomii de fier pierd 2 electroni (oxidare), iar ionii de cupru îi primesc (reducere). Una nu se poate întâmpla fără cealaltă, de aceea o numim reacție redox.', 'Always together', 'Mereu împreună'),
    sl({type:'redox', battery:1}, 'Rusting, burning, batteries and even breathing are redox reactions. In a battery, the moving electrons flow through a wire as electric current.', 'Ruginirea, arderea, bateriile și chiar respirația sunt reacții redox. Într-o baterie, electronii care se mută circulă printr-un fir ca un curent electric.', 'Redox everywhere', 'Redox peste tot'),
   ],
   terms:[tm('oxidation','oxidare','losing electrons','pierdere de electroni'), tm('reduction','reducere','gaining electrons','câștig de electroni'), tm('redox','redox','reduction and oxidation happening together','reducere și oxidare care au loc împreună')],
   quiz:[qz('Losing electrons is called…','Pierderea de electroni se numește…', [['reduction','reducere'],['oxidation','oxidare'],['neutralisation','neutralizare']], 1, 'OIL: Oxidation Is Loss.','Oxidarea înseamnă pierdere.'),
         qz('In a battery, electric current is…','Într-o baterie, curentul electric este…', [['moving electrons','electroni în mișcare'],['moving neutrons','neutroni în mișcare'],['moving protons','protoni în mișcare']], 0, 'Redox pushes electrons through the wire.','Reacția redox împinge electronii prin fir.')],
   try:{tab:'lab', mission:'rule:fe_cuso4', label:L('Plate a nail with copper','Acoperă un cui cu cupru')}},

  {id:'polarity', title:L('Polar molecules','Molecule polare'),
   slides:[
    sl({type:'polar'}, 'In some bonds one atom pulls the shared electrons harder. In water, oxygen pulls harder, so it becomes slightly negative (δ−) and the hydrogens slightly positive (δ+). Water is a polar molecule.', 'În unele legături, un atom trage mai tare de electronii comuni. În apă, oxigenul trage mai tare, așa că devine ușor negativ (δ−), iar hidrogenii ușor pozitivi (δ+). Apa este o moleculă polară.', 'A tug of war for electrons', 'O luptă pentru electroni'),
    sl({type:'hbond'}, 'The δ+ end of one water molecule attracts the δ− end of another. These hydrogen bonds make water sticky, give it a high boiling point and even make ice float.', 'Capătul δ+ al unei molecule de apă atrage capătul δ− al alteia. Aceste legături de hidrogen fac apa lipicioasă, îi dau un punct de fierbere ridicat și chiar fac gheața să plutească.', 'Hydrogen bonds', 'Legături de hidrogen'),
    sl({type:'polar', oil:1}, '“Like dissolves like”: polar water dissolves polar or ionic substances, such as sugar and salt, but not non-polar oil. That is why oil and water separate and why we need soap.', '„Similarul dizolvă similarul”: apa polară dizolvă substanțe polare sau ionice, ca zahărul și sarea, dar nu și uleiul nepolar. De aceea uleiul și apa se separă și avem nevoie de săpun.', 'Like dissolves like', 'Similarul dizolvă similarul'),
   ],
   terms:[tm('polar molecule','moleculă polară','a molecule with a slightly + end and a slightly − end','o moleculă cu un capăt ușor + și unul ușor −'), tm('δ+ / δ−','δ+ / δ−','small partial charges','sarcini parțiale mici'), tm('hydrogen bond','legătură de hidrogen','an attraction between polar molecules like water','o atracție între molecule polare, ca apa')],
   quiz:[qz('Why doesn’t oil dissolve in water?','De ce uleiul nu se dizolvă în apă?', [['Oil is non-polar','Uleiul este nepolar'],['Oil is too heavy','Uleiul este prea greu'],['The water is too cold','Apa e prea rece']], 0, 'Water sticks to water and pushes non-polar oil away.','Apa se lipește de apă și împinge deoparte uleiul nepolar.'),
         qz('Which end of a water molecule is slightly negative?','Ce capăt al moleculei de apă este ușor negativ?', [['The oxygen','Oxigenul'],['The hydrogens','Hidrogenii'],['Neither','Niciunul']], 0, 'Oxygen pulls the shared electrons towards itself.','Oxigenul trage electronii comuni spre el.')],
   try:{tab:'lab', mission:'rule:soap_emulsion', label:L('Mix oil and water with soap','Amestecă uleiul cu apa folosind săpun')}},

  {id:'organic', title:L('Carbon: the chemistry of life','Carbonul: chimia vieții'),
   slides:[
    sl({type:'chain', n:1}, 'A carbon atom can make 4 bonds and link to other carbon atoms in long chains and rings. That is why there are millions of carbon compounds, and why carbon is the backbone of every living thing.', 'Un atom de carbon poate face 4 legături și se poate lega de alți atomi de carbon în lanțuri lungi și inele. De aceea există milioane de compuși ai carbonului, iar carbonul este scheletul oricărei ființe vii.', 'Four bonds', 'Patru legături'),
    sl({type:'chain', grow:1}, 'The simplest ones are hydrocarbons, made only of carbon and hydrogen: methane (1 carbon), ethane (2), propane (3) and butane (4). Longer chains make petrol, wax and oils.', 'Cei mai simpli sunt hidrocarburile, formate doar din carbon și hidrogen: metan (1 carbon), etan (2), propan (3) și butan (4). Lanțurile mai lungi formează benzina, ceara și uleiurile.', 'Hydrocarbons', 'Hidrocarburi'),
    sl({type:'chain', polymer:1}, 'Join thousands of small molecules into giant chains and you get polymers: plastics, the glue in slime and rubber, and in nature, starch, proteins and DNA.', 'Unește mii de molecule mici în lanțuri uriașe și obții polimeri: materiale plastice, lipiciul din slime și cauciucul, iar în natură amidonul, proteinele și ADN-ul.', 'Polymers', 'Polimeri'),
   ],
   terms:[tm('organic chemistry','chimie organică','the chemistry of carbon compounds','chimia compușilor carbonului'), tm('hydrocarbon','hidrocarbură','a compound of only carbon and hydrogen','un compus format doar din carbon și hidrogen'), tm('polymer','polimer','a giant chain of repeating small units','un lanț uriaș din unități mici repetate'), tm('monomer','monomer','one small repeating unit','o unitate mică repetată')],
   quiz:[qz('How many bonds can a carbon atom make?','Câte legături poate face un atom de carbon?', [['2','2'],['4','4'],['6','6']], 1, 'Carbon has 4 outer electrons, so it forms 4 bonds.','Carbonul are 4 electroni exteriori, deci formează 4 legături.'),
         qz('Which of these is a polymer?','Care dintre acestea este un polimer?', [['Salt','Sarea'],['Water','Apa'],['Plastic','Plasticul']], 2, 'Plastics are long chains of repeating units.','Plasticele sunt lanțuri lungi din unități repetate.')],
   try:{tab:'lab', mission:'rule:slime', label:L('Make polymer slime','Fă slime din polimeri')}},
 ]},
];
// ---------- the full curriculum: 4 age stages → modules → lessons ----------
// Order follows the UK KS2–KS3 → GCSE (AQA 8462) → A-level (AQA 7405) sequence and the Romanian
// programme (gimnaziu VII–VIII, liceu IX–XII). Learners may open any lesson; "Continue" follows this order.
COURSES.kids.forEach(tk => tk.lessons.forEach(l => { LESSON_BANK[l.id] = l; }));
const STAGES = [
  {id:'s1', n:1, level:0, ages:'8–11', name:L('Discover','Descoperă'), sub:L('Primary science · KS2 · clasele III–VI','Științe · ciclul primar · clasele III–VI'), modules:[
    {id:'m101', name:L('Chemistry 101: the basics','Chimie 101: noțiunile de bază'), lessons:['matter','atom','elements','molecules','mixtures','changes']},
    {id:'mmat', name:L('Materials and the lab','Materiale și laboratorul'), lessons:['materials','changesstate','separation','safety']}]},
  {id:'s2', n:2, level:1, ages:'11–14', name:L('Foundations','Fundamente'), sub:L('KS3 · clasele VII–VIII','Gimnaziu · clasele VII–VIII'), modules:[
    {id:'mbond', name:L('Atoms, bonds and the periodic table','Atomi, legături și tabelul periodic'), lessons:['bond','bondtypes','periodic','polarity']},
    {id:'mreact', name:L('Chemical reactions','Reacții chimice'), lessons:['reactions','reacttypes','energy','rates','combustion']},
    {id:'macid', name:L('Acids, bases, salts and metals','Acizi, baze, săruri și metale'), lessons:['acids','ions','oxides','metalsreact']},
    {id:'mearth', name:L('Earth and atmosphere','Pământul și atmosfera'), lessons:['earth']}]},
  {id:'s3', n:3, level:2, ages:'14–16', name:L('Core chemistry','Chimie de bază'), sub:L('GCSE · clasele IX–X','Liceu · clasele IX–X'), modules:[
    {id:'mstruct', name:L('Structure and quantities','Structură și cantități'), lessons:['econfig','structures','mole','stoich','concentration']},
    {id:'mchange', name:L('Chemical changes and energy','Transformări chimice și energie'), lessons:['redox','electrolysis','cells','equilibrium','gases']},
    {id:'morg', name:L('Organic chemistry','Chimie organică'), lessons:['organic','hydrocarbons','functional','isomers','biomolecules']},
    {id:'manal', name:L('Analysis and resources','Analiză și resurse'), lessons:['analysis','resources']}]},
  {id:'s4', n:4, level:2, ages:'16–18', name:L('Advanced','Avansat'), sub:L('A-level · clasele XI–XII','Liceu · clasele XI–XII'), modules:[
    {id:'mphys', name:L('Physical chemistry','Chimie fizică'), lessons:['orbitals','shapes','imf','thermo','entropy','kinetics','kc','acidsadv','electrode']},
    {id:'minorg', name:L('Inorganic chemistry','Chimie anorganică'), lessons:['groups','transition']},
    {id:'morg2', name:L('Organic chemistry and analysis','Chimie organică și analiză'), lessons:['mechanisms','optical','carbonyls','aromatic','aminesdna','polymersadv','spectroscopy','nuclear']}]},
];
COURSES.kids = [];
STAGES.forEach(sg => sg.modules.forEach(m => {
  const ls = m.lessons.map(id => LESSON_BANK[id]).filter(Boolean);
  ls.forEach(l => { l.stage = sg; l.module = m; });
  COURSES.kids.push({id:m.id, stage:sg, name:m.name, sub:sg.name, lessons:ls});
}));
function courseTracks(){ return COURSES[AGE] || COURSES[AGE_GROUPS[0].id]; }
let _ALL = null;
function allLessons(){ if(_ALL) return _ALL; const out = []; courseTracks().forEach(tr2 => tr2.lessons.forEach(l => { l.track = tr2.id; out.push(l); })); return (_ALL = out); }
function lessonById(id){ return allLessons().find(l => l.id === id); }
function stageForLevel(lv){ return lv >= 2 ? STAGES[2] : STAGES[lv] || STAGES[0]; }
// which lesson explains a lab reaction
const RULE_LESSON = {salt_dissolve:'mixtures', sugar_dissolve:'mixtures', sand_water:'mixtures', cuso4_dissolve:'mixtures', soda_dissolve:'mixtures', evaporate:'mixtures', geyser:'mixtures', cola_salt:'mixtures',
  oil_water:'polarity', soap_emulsion:'polarity', soap_water:'polarity', magic_milk:'polarity', milk_dots:'polarity',
  acid_carb:'acids', neutralize:'acids', indicator:'acids', cacl2_soda:'ions', milk_curd:'acids',
  na_water:'periodic', k_water:'periodic', li_water:'periodic', cs_water:'periodic', flame:'atom',
  fe_cuso4:'redox', cu_ag:'redox', mg_acid:'redox', thermite:'redox', al_cucl2:'redox', al_lazy:'redox', cu_hno3:'redox', iodine_vitc:'redox', mirror:'redox', traffic:'redox', chameleon:'redox',
  agno3_cl:'ions', cuso4_base:'ions', golden:'ions', agi:'ions', fe_base:'ions', fe_scn:'ions', cu_amm:'ions', garden:'ions', cocl2_heat:'ions', cocl2b_water:'ions',
  h2o2_yeast:'rates', h2o2_ki:'rates', iodine_clock:'rates', luminol:'energy',
  coldpack:'energy', hotpack:'energy', mg_burn:'energy', kmno4_glycerol:'energy', h2so4_water:'energy', cuso4w_water:'energy', cuso4_heat:'energy', soda_heat:'changes', sugar_caramel:'changes', sugar_burn:'changes', sugar_snake:'changes', acid_snake:'changes',
  dryice_water:'matter', dryice_soap:'matter', dryice_dry:'matter', hotice:'matter', snow:'organic', slime:'organic', iodine_starch:'organic',
  zn_acid:'metalsreact', zn_cuso4:'metalsreact', limewater:'analysis', bromine:'hydrocarbons', bromine_neg:'hydrocarbons', ester:'functional', dichromate:'functional', saponify:'functional',
  benedict:'biomolecules', benedict_neg:'biomolecules', biuret:'biomolecules', ferment:'biomolecules', feii_base:'analysis', bacl2:'analysis', agbr:'analysis', halogen_disp:'groups',
  mno2:'rates', thio:'kinetics', thio_start:'rates', chromate:'equilibrium', chromate_fwd:'equilibrium', indicator2:'acids', titration:'concentration', electrolysis:'electrolysis', cell:'cells'};
Object.assign(RULE_LESSON, {cocl2_heat:'equilibrium', cocl2b_water:'equilibrium', fe_scn:'analysis', cu_amm:'transition', agi:'analysis', mg_burn:'combustion', sugar_burn:'combustion', na_water:'metalsreact', k_water:'metalsreact', li_water:'metalsreact', cs_water:'metalsreact', flame:'analysis', mirror:'carbonyls'});
